# Generated by Django 3.0.7 on 2020-07-26 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('bn_name', models.CharField(max_length=250)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True)),
                ('url', models.URLField(blank=True, default=None, max_length=500, null=True)),
                ('is_active', models.NullBooleanField(default=True)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('insert_user', models.CharField(blank=True, max_length=30, null=True)),
                ('insert_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('update_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('bn_name', models.CharField(max_length=250)),
                ('url', models.URLField(blank=True, default=None, max_length=500, null=True)),
                ('is_active', models.NullBooleanField(default=True)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('insert_user', models.CharField(blank=True, max_length=30, null=True)),
                ('insert_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('update_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upzilas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upzila_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('bn_name', models.CharField(max_length=250)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True)),
                ('url', models.URLField(blank=True, default=None, max_length=500, null=True)),
                ('is_active', models.NullBooleanField(default=True)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('insert_user', models.CharField(blank=True, max_length=30, null=True)),
                ('insert_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('update_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangladesh_geocode.Districts')),
            ],
        ),
        migrations.CreateModel(
            name='Unions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('bn_name', models.CharField(max_length=250)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True)),
                ('url', models.URLField(blank=True, default=None, max_length=500, null=True)),
                ('is_active', models.NullBooleanField(default=True)),
                ('is_delete', models.NullBooleanField(default=False)),
                ('insert_user', models.CharField(blank=True, max_length=30, null=True)),
                ('insert_date', models.DateTimeField(auto_now=True)),
                ('update_user', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('update_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('upzila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangladesh_geocode.Upzilas')),
            ],
        ),
        migrations.AddField(
            model_name='districts',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangladesh_geocode.Divisions'),
        ),
    ]
