# Generated by Django 3.0.7 on 2020-07-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangladesh_geocode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisions',
            name='division_id',
            field=models.IntegerField(default=0),
        ),
    ]
