# Generated by Django 3.0.7 on 2020-07-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangladesh_geocode', '0002_divisions_division_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='district_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unions',
            name='union_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upzilas',
            name='upzila_id',
            field=models.IntegerField(default=0),
        ),
    ]
