# Generated by Django 3.0.7 on 2020-06-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='violence',
            new_name='violance',
        ),
    ]
