# Generated by Django 3.0.7 on 2020-06-17 00:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_item_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_ps', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('crime_count', models.DecimalField(decimal_places=0, max_digits=5)),
                ('crime_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CrimeCount')),
            ],
        ),
    ]
