# Generated by Django 3.0.7 on 2020-06-17 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_crimecount_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='Date',
        ),
    ]
