# Generated by Django 3.0.7 on 2020-06-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200617_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='crime_list',
        ),
        migrations.DeleteModel(
            name='CrimeCount',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
