# Generated by Django 3.0.7 on 2020-06-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VictimApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=50)),
                ('incident_type', models.CharField(choices=[('rape', 'Rape'), ('physical_torture', 'Attacking Physically'), ('metal_torture', 'Mental Torture')], default='metal_torture', max_length=20)),
                ('incident_date', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unspecified', 'Unspecified')], default='female', max_length=15)),
                ('relation_with_criminal', models.CharField(choices=[('friend', 'Friend(s)'), ('unknown', 'Unknown'), ('relative', 'Relative(s)'), ('in-laws', 'In laws')], default='unknown', max_length=20)),
                ('witness', models.BooleanField(default=False)),
                ('witness_name', models.CharField(default='No name', max_length=20)),
                ('informed_authority', models.BooleanField(default=False)),
                ('authority_name', models.CharField(choices=[('police', 'Police'), ('UNO', 'UNO'), ('chairman', 'Chairman'), ('member', 'Member')], default='None', max_length=20)),
                ('description', models.CharField(default='', max_length=300)),
                ('current_status_of_victim', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
