# Generated by Django 3.0.7 on 2020-06-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victim_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='victimapplication',
            name='address_1',
            field=models.CharField(default='n/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='victimapplication',
            name='address_2',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='victimapplication',
            name='address_3',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='victimapplication',
            name='address_4',
            field=models.CharField(default='Na', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='victimapplication',
            name='address_5',
            field=models.CharField(default='Bangladesh', max_length=20),
        ),
    ]
